services:
  database:
    image: "postgres:16"
    # # container_name: postgres_test
    environment:
      POSTGRES_USER: kush
      POSTGRES_PASSWORD: kushprivate
      POSTGRES_DB: shelter
    volumes:
      - database_data:/var/lib/postgresql/data  
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  etl:
    build: .
    command: https://shelterdata.s3.amazonaws.com/shelter1000.csv
    depends_on:
      - database   
volumes:
  database_data: